In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("인천시_gis건물_일반_집합_주차면만_50면이상_5179.csv", encoding  = "CP949")

In [3]:
df.head(1)

                             A0  주차면수 a0_2  주차면수_2
0  1995164410394391683600000000  58.0  NaN     NaN

In [4]:
len(df)

2800

In [5]:
df.iloc[:, [0,1]].isnull().sum()

A0      2045
주차면수    2045
dtype: int64

In [6]:
df.iloc[:, [2,3]].isnull().sum()

a0_2      754
주차면수_2    754
dtype: int64

In [7]:
s1 = df.iloc[:755,[0,1]].copy()
s1

                               A0   주차면수
0    1995164410394391683600000000   58.0
1    2011169624484475047400000000   65.0
2    2010176113984471323800000000  571.0
3    2010332430684184758500000000   65.0
4    2012175777094440871400000000  130.0
5    2005171340434491671600000000  111.0
6    2007174759034393190500000000   70.0
7    2014173801724345606000000000   52.0
8    1992176199564440608900000000   51.0
9    2003169020964415450900000000  281.0
10   2010174782654476616400000000  101.0
11   2005176399284450346300000000   57.0
12   2014168471294478306400000000   56.0
13   2010166326994387622300000000   85.0
14   2011169924434483947000000000   63.0
15   2010173927064472433200000000   69.0
16   1999171881404360387700000000  129.0
17   1999171489324542600000000000   52.0
18   1985176249894465594100000000   90.0
19   1985176278294465921500000000  114.0
20   1993171560394343462700000000   60.0
21   2004177124164502574800000000   51.0
22   1993169543474406204600000000   80.0
23   1989175400814459957800000000   72.0
24   0000168668294437350200000000  101.0
25   0000168472024437250500000000  101.0
26   0000168510794436993600000000  101.0
27   1987174854764385545200000000  108.0
28   1996176506434404400200000000   54.0
29   2011167222024388307400000000  109.0
..                            ...    ...
725  1999164711064414979700000000  130.0
726  2017165714224379058200000000   88.0
727  2014165829904550700200000000   54.0
728  1996170889324420015500000000  334.0
729  1994170420614425086500000000   66.0
730  2010168175214403727500000000  109.0
731  2003175547774441070900000000   60.0
732  1999174897384490422100000000  104.0
733  1986171690484401011900000000   58.0
734  2014172488344343226900000000  108.0
735  2014172136344489376800000000  471.0
736  1982171676924400544900000000  114.0
737  2014173271924324400800000000   84.0
738  2010177386244481497900000000   58.0
739  2007177105584463993100000000   79.0
740  2011166076394439939300000000  110.0
741  2011166079794439166800000000  110.0
742  2007174954624462276800000000   54.0
743  2011166330084440108200000000  110.0
744  2011166238214439830900000000  110.0
745  2011166115454439735300000000  110.0
746  2007177120704383510400000000   80.0
747  2011166352064440119500000000  110.0
748  2004172101504514288600000000   55.0
749  2011166352434438543700000000  110.0
750  2011166099014439102100000000  110.0
751  2005167651324407423100000000   59.0
752  2004172133464513928600000000   55.0
753  1997165459984474990800000000   68.0
754  2009169285284410326000000000   71.0

[755 rows x 2 columns]

In [8]:
s2 = df.iloc[755:,[2,3]].copy()
s2.rename(columns = {
    'a0_2' : 'A0',
    '주차면수_2' : '주차면수'
}, inplace = True)
s2.index = range(len(s2))
s2

                                A0   주차면수
0     1992171768744357776900000000  101.0
1     2011174271054331661900000000  469.0
2     2001172114014404188300000000  103.0
3     2011174306974331721800000000  469.0
4     2011174317094331370300000000  469.0
5     1992171763504357255000000000  101.0
6     1994171172394358422900000000  689.0
7     1994171100364357833100000000  689.0
8     1994171151234357092300000000  469.0
9     1994171225304357703400000000  689.0
10    1994171080624357501400000000  689.0
11    1994171238974358353200000000  689.0
12    1994171087674358508400000000  689.0
13    1993170834774358676300000000  273.0
14    1993170936564358639700000000  273.0
15    2007171819294404559600000000   96.0
16    1993171001134357956700000000  273.0
17    1993170940694358118600000000  273.0
18    1994171043644356205400000000  291.0
19    1994170948004356638900000000  291.0
20    2006175505554476919100000000  121.0
21    1994170984844356933700000000  291.0
22    1994171006394355910100000000  291.0
23    1997170902894489969700000000  607.0
24    1994171021594357230300000000  291.0
25    1997170804934490480300000000  607.0
26    1997170765354489562200000000  607.0
27    1996171559794433104000000000  398.0
28    1997170840314489987800000000  607.0
29    1996171565214433568000000000  398.0
...                            ...    ...
2015  1992172639104356322800000000  295.0
2016  1992172503524354213100000000  295.0
2017  1992172699804354318500000000  332.0
2018  1992172712534353811200000000  332.0
2019  1992172751904354367600000000  332.0
2020  2005175760874435212900000000  320.0
2021  1992172713884356375000000000  295.0
2022  1992172624894354386200000000  332.0
2023  1992172591314353910100000000  332.0
2024  1992172568214355127200000000  116.0
2025  1997170802484492235300000000  423.0
2026  1993171934394357594200000000  785.0
2027  1997170865574491945600000000  423.0
2028  1993172029014357537700000000  785.0
2029  1997170846714491673300000000  423.0
2030  1993171929024357079500000000  785.0
2031  1997170790014491696500000000  423.0
2032  1993171962574356494300000000  785.0
2033  1997170853714492215400000000  423.0
2034  1993171932684356075800000000  785.0
2035  2006174546764444758500000000  112.0
2036  1993171849064355884600000000  785.0
2037  1993172114384356523300000000  785.0
2038  1993172118894356958700000000  785.0
2039  1993172123724357434300000000  785.0
2040  1993172023134356963300000000  785.0
2041  2011174093704332848700000000  300.0
2042  1992171761044356733800000000  101.0
2043  1992171758184356998800000000  101.0
2044  1992171766254357515900000000  101.0

[2045 rows x 2 columns]

In [9]:
df2 = pd.concat([ s1, s2],axis = 0)
df2

                                A0   주차면수
0     1995164410394391683600000000   58.0
1     2011169624484475047400000000   65.0
2     2010176113984471323800000000  571.0
3     2010332430684184758500000000   65.0
4     2012175777094440871400000000  130.0
5     2005171340434491671600000000  111.0
6     2007174759034393190500000000   70.0
7     2014173801724345606000000000   52.0
8     1992176199564440608900000000   51.0
9     2003169020964415450900000000  281.0
10    2010174782654476616400000000  101.0
11    2005176399284450346300000000   57.0
12    2014168471294478306400000000   56.0
13    2010166326994387622300000000   85.0
14    2011169924434483947000000000   63.0
15    2010173927064472433200000000   69.0
16    1999171881404360387700000000  129.0
17    1999171489324542600000000000   52.0
18    1985176249894465594100000000   90.0
19    1985176278294465921500000000  114.0
20    1993171560394343462700000000   60.0
21    2004177124164502574800000000   51.0
22    1993169543474406204600000000   80.0
23    1989175400814459957800000000   72.0
24    0000168668294437350200000000  101.0
25    0000168472024437250500000000  101.0
26    0000168510794436993600000000  101.0
27    1987174854764385545200000000  108.0
28    1996176506434404400200000000   54.0
29    2011167222024388307400000000  109.0
...                            ...    ...
2015  1992172639104356322800000000  295.0
2016  1992172503524354213100000000  295.0
2017  1992172699804354318500000000  332.0
2018  1992172712534353811200000000  332.0
2019  1992172751904354367600000000  332.0
2020  2005175760874435212900000000  320.0
2021  1992172713884356375000000000  295.0
2022  1992172624894354386200000000  332.0
2023  1992172591314353910100000000  332.0
2024  1992172568214355127200000000  116.0
2025  1997170802484492235300000000  423.0
2026  1993171934394357594200000000  785.0
2027  1997170865574491945600000000  423.0
2028  1993172029014357537700000000  785.0
2029  1997170846714491673300000000  423.0
2030  1993171929024357079500000000  785.0
2031  1997170790014491696500000000  423.0
2032  1993171962574356494300000000  785.0
2033  1997170853714492215400000000  423.0
2034  1993171932684356075800000000  785.0
2035  2006174546764444758500000000  112.0
2036  1993171849064355884600000000  785.0
2037  1993172114384356523300000000  785.0
2038  1993172118894356958700000000  785.0
2039  1993172123724357434300000000  785.0
2040  1993172023134356963300000000  785.0
2041  2011174093704332848700000000  300.0
2042  1992171761044356733800000000  101.0
2043  1992171758184356998800000000  101.0
2044  1992171766254357515900000000  101.0

[2800 rows x 2 columns]

In [10]:
df2.index = range(len(df2))

In [22]:
df3 = df2.groupby(['A0']).count()

df3['A0'] = df3.index

df3.index = range(len(df3))

df3 = df3.iloc[:, [1,0]]

df3[df3['주차면수'] >= 2 ]

                               A0  주차면수
653  1994170543404341610000000000     2

In [26]:
rm_li = list(df3.loc[df3['주차면수'] >= 2 ,'A0'])
rm_li

['1994170543404341610000000000']

In [12]:
df2[df2['A0'] == '1994170543404341610000000000']

                               A0    주차면수
353  1994170543404341610000000000  1018.0
354  1994170543404341610000000000  1018.0

In [14]:
df2.iloc[350:358,:]

                               A0    주차면수
350  1996176431634404758500000000    54.0
351  2012164577314535681900000000    64.0
352  2012164568584535693700000000    64.0
353  1994170543404341610000000000  1018.0
354  1994170543404341610000000000  1018.0
355  2012164571404535529100000000    64.0
356  2012164578464535472700000000    64.0
357  2011164594854392512400000000   222.0

In [27]:
df

,A0,주차면수,a0_2,주차면수_2
0,1995164410394391683600000000,58.0,NaN,NaN
1,2011169624484475047400000000,65.0,NaN,NaN
2,2010176113984471323800000000,571.0,NaN,NaN
3,2010332430684184758500000000,65.0,NaN,NaN
4,2012175777094440871400000000,130.0,NaN,NaN
5,2005171340434491671600000000,111.0,NaN,NaN
6,2007174759034393190500000000,70.0,NaN,NaN
7,2014173801724345606000000000,52.0,NaN,NaN
8,1992176199564440608900000000,51.0,NaN,NaN
9,2003169020964415450900000000,281.0,NaN,NaN
10,2010174782654476616400000000,101.0,NaN,NaN
11,2005176399284450346300000000,57.0,NaN,NaN
12,2014168471294478306400000000,56.0,NaN,NaN
13,2010166326994387622300000000,85.0,NaN,NaN
14,2011169924434483947000000000,63.0,NaN,NaN
15,2010173927064472433200000000,69.0,NaN,NaN
16,1999171881404360387700000000,129.0,NaN,NaN
17,1999171489324542600000000000,52.0,NaN,NaN
18,1985176249894465594100000000,90.0,NaN,NaN
19,1985176278294465921500000000,114.0,NaN,NaN
20,1993171560394343462700000000,60.0,NaN,NaN
21,2004177124164502574800000000,51.0,NaN,NaN
22,1993169543474406204600000000,80.0,NaN,NaN
23,1989175400814459957800000000,72.0,NaN,NaN
24,0000168668294437350200000000,101.0,NaN,NaN
25,0000168472024437250500000000,101.0,NaN,NaN
26,0000168510794436993600000000,101.0,NaN,NaN
27,1987174854764385545200000000,108.0,NaN,NaN
28,1996176506434404400200000000,54.0,NaN,NaN
29,2011167222024388307400000000,109.0,NaN,NaN
...,...,...,...,...
2770,NaN,NaN,1992172639104356322800000000,295.0
2771,NaN,NaN,1992172503524354213100000000,295.0
2772,NaN,NaN,1992172699804354318500000000,332.0
2773,NaN,NaN,1992172712534353811200000000,332.0
2774,NaN,NaN,1992172751904354367600000000,332.0
2775,NaN,NaN,2005175760874435212900000000,320.0
2776,NaN,NaN,1992172713884356375000000000,295.0
2777,NaN,NaN,1992172624894354386200000000,332.0
2778,NaN,NaN,1992172591314353910100000000,332.0
2779,NaN,NaN,1992172568214355127200000000,116.0
2780,NaN,NaN,1997170802484492235300000000,423.0
2781,NaN,NaN,1993171934394357594200000000,785.0
2782,NaN,NaN,1997170865574491945600000000,423.0
2783,NaN,NaN,1993172029014357537700000000,785.0
2784,NaN,NaN,1997170846714491673300000000,423.0
2785,NaN,NaN,1993171929024357079500000000,785.0
2786,NaN,NaN,1997170790014491696500000000,423.0
2787,NaN,NaN,1993171962574356494300000000,785.0
2788,NaN,NaN,1997170853714492215400000000,423.0
2789,NaN,NaN,1993171932684356075800000000,785.0
2790,NaN,NaN,2006174546764444758500000000,112.0
2791,NaN,NaN,1993171849064355884600000000,785.0
2792,NaN,NaN,1993172114384356523300000000,785.0
2793,NaN,NaN,1993172118894356958700000000,785.0
2794,NaN,NaN,1993172123724357434300000000,785.0
2795,NaN,NaN,1993172023134356963300000000,785.0
2796,NaN,NaN,2011174093704332848700000000,300.0
2797,NaN,NaN,1992171761044356733800000000,101.0
2798,NaN,NaN,1992171758184356998800000000,101.0
2799,NaN,NaN,1992171766254357515900000000,101.0

In [35]:
(df.iloc[:,0].isnull())

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
        ...
2770     True
2771     True
2772     True
2773     True
2774     True
2775     True
2776     True
2777     True
2778     True
2779     True
2780     True
2781     True
2782     True
2783     True
2784     True
2785     True
2786     True
2787     True
2788     True
2789     True
2790     True
2791     True
2792     True
2793     True
2794     True
2795     True
2796     True
2797     True
2798     True
2799     True
Name: A0, Length: 2800, dtype: bool

In [47]:
s1 = df[ df.iloc[:,0].isnull() == 0] 

del s1['a0_2']
del s1['주차면수_2']

s1

                               A0   주차면수
0    1995164410394391683600000000   58.0
1    2011169624484475047400000000   65.0
2    2010176113984471323800000000  571.0
3    2010332430684184758500000000   65.0
4    2012175777094440871400000000  130.0
5    2005171340434491671600000000  111.0
6    2007174759034393190500000000   70.0
7    2014173801724345606000000000   52.0
8    1992176199564440608900000000   51.0
9    2003169020964415450900000000  281.0
10   2010174782654476616400000000  101.0
11   2005176399284450346300000000   57.0
12   2014168471294478306400000000   56.0
13   2010166326994387622300000000   85.0
14   2011169924434483947000000000   63.0
15   2010173927064472433200000000   69.0
16   1999171881404360387700000000  129.0
17   1999171489324542600000000000   52.0
18   1985176249894465594100000000   90.0
19   1985176278294465921500000000  114.0
20   1993171560394343462700000000   60.0
21   2004177124164502574800000000   51.0
22   1993169543474406204600000000   80.0
23   1989175400814459957800000000   72.0
24   0000168668294437350200000000  101.0
25   0000168472024437250500000000  101.0
26   0000168510794436993600000000  101.0
27   1987174854764385545200000000  108.0
28   1996176506434404400200000000   54.0
29   2011167222024388307400000000  109.0
..                            ...    ...
725  1999164711064414979700000000  130.0
726  2017165714224379058200000000   88.0
727  2014165829904550700200000000   54.0
728  1996170889324420015500000000  334.0
729  1994170420614425086500000000   66.0
730  2010168175214403727500000000  109.0
731  2003175547774441070900000000   60.0
732  1999174897384490422100000000  104.0
733  1986171690484401011900000000   58.0
734  2014172488344343226900000000  108.0
735  2014172136344489376800000000  471.0
736  1982171676924400544900000000  114.0
737  2014173271924324400800000000   84.0
738  2010177386244481497900000000   58.0
739  2007177105584463993100000000   79.0
740  2011166076394439939300000000  110.0
741  2011166079794439166800000000  110.0
742  2007174954624462276800000000   54.0
743  2011166330084440108200000000  110.0
744  2011166238214439830900000000  110.0
745  2011166115454439735300000000  110.0
746  2007177120704383510400000000   80.0
747  2011166352064440119500000000  110.0
748  2004172101504514288600000000   55.0
749  2011166352434438543700000000  110.0
750  2011166099014439102100000000  110.0
751  2005167651324407423100000000   59.0
752  2004172133464513928600000000   55.0
753  1997165459984474990800000000   68.0
754  2009169285284410326000000000   71.0

[755 rows x 2 columns]

In [56]:
s1.groupby(['A0']).count()[s1.groupby(['A0']).count()['주차면수'] >=2]
s1
s1 = s1.drop_duplicates(['A0'], keep = 'first')
s1

                               A0   주차면수
0    1995164410394391683600000000   58.0
1    2011169624484475047400000000   65.0
2    2010176113984471323800000000  571.0
3    2010332430684184758500000000   65.0
4    2012175777094440871400000000  130.0
5    2005171340434491671600000000  111.0
6    2007174759034393190500000000   70.0
7    2014173801724345606000000000   52.0
8    1992176199564440608900000000   51.0
9    2003169020964415450900000000  281.0
10   2010174782654476616400000000  101.0
11   2005176399284450346300000000   57.0
12   2014168471294478306400000000   56.0
13   2010166326994387622300000000   85.0
14   2011169924434483947000000000   63.0
15   2010173927064472433200000000   69.0
16   1999171881404360387700000000  129.0
17   1999171489324542600000000000   52.0
18   1985176249894465594100000000   90.0
19   1985176278294465921500000000  114.0
20   1993171560394343462700000000   60.0
21   2004177124164502574800000000   51.0
22   1993169543474406204600000000   80.0
23   1989175400814459957800000000   72.0
24   0000168668294437350200000000  101.0
25   0000168472024437250500000000  101.0
26   0000168510794436993600000000  101.0
27   1987174854764385545200000000  108.0
28   1996176506434404400200000000   54.0
29   2011167222024388307400000000  109.0
..                            ...    ...
725  1999164711064414979700000000  130.0
726  2017165714224379058200000000   88.0
727  2014165829904550700200000000   54.0
728  1996170889324420015500000000  334.0
729  1994170420614425086500000000   66.0
730  2010168175214403727500000000  109.0
731  2003175547774441070900000000   60.0
732  1999174897384490422100000000  104.0
733  1986171690484401011900000000   58.0
734  2014172488344343226900000000  108.0
735  2014172136344489376800000000  471.0
736  1982171676924400544900000000  114.0
737  2014173271924324400800000000   84.0
738  2010177386244481497900000000   58.0
739  2007177105584463993100000000   79.0
740  2011166076394439939300000000  110.0
741  2011166079794439166800000000  110.0
742  2007174954624462276800000000   54.0
743  2011166330084440108200000000  110.0
744  2011166238214439830900000000  110.0
745  2011166115454439735300000000  110.0
746  2007177120704383510400000000   80.0
747  2011166352064440119500000000  110.0
748  2004172101504514288600000000   55.0
749  2011166352434438543700000000  110.0
750  2011166099014439102100000000  110.0
751  2005167651324407423100000000   59.0
752  2004172133464513928600000000   55.0
753  1997165459984474990800000000   68.0
754  2009169285284410326000000000   71.0

[754 rows x 2 columns]

In [48]:
s2 = df[ df.iloc[:,2].isnull() == 0] 

del s2['A0']
del s2['주차면수']

s2

                              a0_2  주차면수_2
353   1994170533874341560700000000  1018.0
755   1992171768744357776900000000   101.0
756   2011174271054331661900000000   469.0
757   2001172114014404188300000000   103.0
758   2011174306974331721800000000   469.0
759   2011174317094331370300000000   469.0
760   1992171763504357255000000000   101.0
761   1994171172394358422900000000   689.0
762   1994171100364357833100000000   689.0
763   1994171151234357092300000000   469.0
764   1994171225304357703400000000   689.0
765   1994171080624357501400000000   689.0
766   1994171238974358353200000000   689.0
767   1994171087674358508400000000   689.0
768   1993170834774358676300000000   273.0
769   1993170936564358639700000000   273.0
770   2007171819294404559600000000    96.0
771   1993171001134357956700000000   273.0
772   1993170940694358118600000000   273.0
773   1994171043644356205400000000   291.0
774   1994170948004356638900000000   291.0
775   2006175505554476919100000000   121.0
776   1994170984844356933700000000   291.0
777   1994171006394355910100000000   291.0
778   1997170902894489969700000000   607.0
779   1994171021594357230300000000   291.0
780   1997170804934490480300000000   607.0
781   1997170765354489562200000000   607.0
782   1996171559794433104000000000   398.0
783   1997170840314489987800000000   607.0
...                            ...     ...
2770  1992172639104356322800000000   295.0
2771  1992172503524354213100000000   295.0
2772  1992172699804354318500000000   332.0
2773  1992172712534353811200000000   332.0
2774  1992172751904354367600000000   332.0
2775  2005175760874435212900000000   320.0
2776  1992172713884356375000000000   295.0
2777  1992172624894354386200000000   332.0
2778  1992172591314353910100000000   332.0
2779  1992172568214355127200000000   116.0
2780  1997170802484492235300000000   423.0
2781  1993171934394357594200000000   785.0
2782  1997170865574491945600000000   423.0
2783  1993172029014357537700000000   785.0
2784  1997170846714491673300000000   423.0
2785  1993171929024357079500000000   785.0
2786  1997170790014491696500000000   423.0
2787  1993171962574356494300000000   785.0
2788  1997170853714492215400000000   423.0
2789  1993171932684356075800000000   785.0
2790  2006174546764444758500000000   112.0
2791  1993171849064355884600000000   785.0
2792  1993172114384356523300000000   785.0
2793  1993172118894356958700000000   785.0
2794  1993172123724357434300000000   785.0
2795  1993172023134356963300000000   785.0
2796  2011174093704332848700000000   300.0
2797  1992171761044356733800000000   101.0
2798  1992171758184356998800000000   101.0
2799  1992171766254357515900000000   101.0

[2046 rows x 2 columns]

In [53]:
s2.groupby(['a0_2']).count()[s2.groupby(['a0_2']).count()['주차면수_2'] >=2]

                              주차면수_2
a0_2
1994170533874341560700000000       2

In [54]:
s2 = s2.drop_duplicates(['a0_2'], keep = 'first')
s2

                              a0_2  주차면수_2
353   1994170533874341560700000000  1018.0
755   1992171768744357776900000000   101.0
756   2011174271054331661900000000   469.0
757   2001172114014404188300000000   103.0
758   2011174306974331721800000000   469.0
759   2011174317094331370300000000   469.0
760   1992171763504357255000000000   101.0
761   1994171172394358422900000000   689.0
762   1994171100364357833100000000   689.0
763   1994171151234357092300000000   469.0
764   1994171225304357703400000000   689.0
765   1994171080624357501400000000   689.0
766   1994171238974358353200000000   689.0
767   1994171087674358508400000000   689.0
768   1993170834774358676300000000   273.0
769   1993170936564358639700000000   273.0
770   2007171819294404559600000000    96.0
771   1993171001134357956700000000   273.0
772   1993170940694358118600000000   273.0
773   1994171043644356205400000000   291.0
774   1994170948004356638900000000   291.0
775   2006175505554476919100000000   121.0
776   1994170984844356933700000000   291.0
777   1994171006394355910100000000   291.0
778   1997170902894489969700000000   607.0
779   1994171021594357230300000000   291.0
780   1997170804934490480300000000   607.0
781   1997170765354489562200000000   607.0
782   1996171559794433104000000000   398.0
783   1997170840314489987800000000   607.0
...                            ...     ...
2770  1992172639104356322800000000   295.0
2771  1992172503524354213100000000   295.0
2772  1992172699804354318500000000   332.0
2773  1992172712534353811200000000   332.0
2774  1992172751904354367600000000   332.0
2775  2005175760874435212900000000   320.0
2776  1992172713884356375000000000   295.0
2777  1992172624894354386200000000   332.0
2778  1992172591314353910100000000   332.0
2779  1992172568214355127200000000   116.0
2780  1997170802484492235300000000   423.0
2781  1993171934394357594200000000   785.0
2782  1997170865574491945600000000   423.0
2783  1993172029014357537700000000   785.0
2784  1997170846714491673300000000   423.0
2785  1993171929024357079500000000   785.0
2786  1997170790014491696500000000   423.0
2787  1993171962574356494300000000   785.0
2788  1997170853714492215400000000   423.0
2789  1993171932684356075800000000   785.0
2790  2006174546764444758500000000   112.0
2791  1993171849064355884600000000   785.0
2792  1993172114384356523300000000   785.0
2793  1993172118894356958700000000   785.0
2794  1993172123724357434300000000   785.0
2795  1993172023134356963300000000   785.0
2796  2011174093704332848700000000   300.0
2797  1992171761044356733800000000   101.0
2798  1992171758184356998800000000   101.0
2799  1992171766254357515900000000   101.0

[2045 rows x 2 columns]

In [59]:
s2.rename( columns = {
    'a0_2' : 'A0'
    , '주차면수_2' : '주차면수'
}, inplace = True)

C:\Users\USER\Anaconda3\lib\site-packages\pandas\core\frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

In [60]:
s3 = pd.concat([s1,s2], axis = 0)
s3

                                A0   주차면수
0     1995164410394391683600000000   58.0
1     2011169624484475047400000000   65.0
2     2010176113984471323800000000  571.0
3     2010332430684184758500000000   65.0
4     2012175777094440871400000000  130.0
5     2005171340434491671600000000  111.0
6     2007174759034393190500000000   70.0
7     2014173801724345606000000000   52.0
8     1992176199564440608900000000   51.0
9     2003169020964415450900000000  281.0
10    2010174782654476616400000000  101.0
11    2005176399284450346300000000   57.0
12    2014168471294478306400000000   56.0
13    2010166326994387622300000000   85.0
14    2011169924434483947000000000   63.0
15    2010173927064472433200000000   69.0
16    1999171881404360387700000000  129.0
17    1999171489324542600000000000   52.0
18    1985176249894465594100000000   90.0
19    1985176278294465921500000000  114.0
20    1993171560394343462700000000   60.0
21    2004177124164502574800000000   51.0
22    1993169543474406204600000000   80.0
23    1989175400814459957800000000   72.0
24    0000168668294437350200000000  101.0
25    0000168472024437250500000000  101.0
26    0000168510794436993600000000  101.0
27    1987174854764385545200000000  108.0
28    1996176506434404400200000000   54.0
29    2011167222024388307400000000  109.0
...                            ...    ...
2770  1992172639104356322800000000  295.0
2771  1992172503524354213100000000  295.0
2772  1992172699804354318500000000  332.0
2773  1992172712534353811200000000  332.0
2774  1992172751904354367600000000  332.0
2775  2005175760874435212900000000  320.0
2776  1992172713884356375000000000  295.0
2777  1992172624894354386200000000  332.0
2778  1992172591314353910100000000  332.0
2779  1992172568214355127200000000  116.0
2780  1997170802484492235300000000  423.0
2781  1993171934394357594200000000  785.0
2782  1997170865574491945600000000  423.0
2783  1993172029014357537700000000  785.0
2784  1997170846714491673300000000  423.0
2785  1993171929024357079500000000  785.0
2786  1997170790014491696500000000  423.0
2787  1993171962574356494300000000  785.0
2788  1997170853714492215400000000  423.0
2789  1993171932684356075800000000  785.0
2790  2006174546764444758500000000  112.0
2791  1993171849064355884600000000  785.0
2792  1993172114384356523300000000  785.0
2793  1993172118894356958700000000  785.0
2794  1993172123724357434300000000  785.0
2795  1993172023134356963300000000  785.0
2796  2011174093704332848700000000  300.0
2797  1992171761044356733800000000  101.0
2798  1992171758184356998800000000  101.0
2799  1992171766254357515900000000  101.0

[2799 rows x 2 columns]