In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("인천시_격자_100M_20_60대_합.csv", encoding = "CP949")

In [6]:
df.head()

        gid  20대_val  30대_val  40대_val  50대_val  60대_val
0  가사462996      NaN      NaN      NaN      NaN      NaN
1  가사462997      NaN      NaN      NaN      NaN      NaN
2  가사462998      NaN      NaN      NaN      NaN      NaN
3  가사462999      NaN      NaN      NaN      NaN      NaN
4  가사463995      NaN      NaN      NaN      NaN      NaN

In [10]:
df2 = df.fillna(int(0))
df2.head()

        gid  20대_val  30대_val  40대_val  50대_val  60대_val
0  가사462996      0.0      0.0      0.0      0.0      0.0
1  가사462997      0.0      0.0      0.0      0.0      0.0
2  가사462998      0.0      0.0      0.0      0.0      0.0
3  가사462999      0.0      0.0      0.0      0.0      0.0
4  가사463995      0.0      0.0      0.0      0.0      0.0

In [12]:
df2['20-60대_합'] =  df2.iloc[:,1] + df2.iloc[:,2] + df2.iloc[:,3] + df2.iloc[:,4] + df2.iloc[:,5]

In [15]:
df2.sort_values('20-60대_합', ascending = False)

             gid  20대_val  30대_val  40대_val  50대_val  60대_val  20-60대_합
109697  다사331367    316.0    974.0    642.0    345.0    242.0    2519.0
82893   다사231329    394.0    467.0    504.0    520.0    198.0    2083.0
75924   다사168440    261.0    500.0    738.0    337.0    175.0    2011.0
83294   다사232491    253.0    625.0    556.0    329.0    155.0    1918.0
87876   다사249363    256.0    231.0    324.0    325.0    206.0    1342.0
101590  다사296422    286.0    220.0    248.0    354.0    232.0    1340.0
88128   다사250312    259.0    216.0    397.0    302.0    150.0    1324.0
101618  다사296450    249.0    212.0    297.0    294.0    237.0    1289.0
96563   다사277476    269.0    245.0    164.0    333.0    227.0    1238.0
93592   다사267471    232.0    227.0    223.0    310.0    241.0    1233.0
96296   다사276498    294.0    193.0    232.0    344.0    163.0    1226.0
109605  다사330484    199.0    230.0    287.0    307.0    116.0    1139.0
100008  다사290401    211.0    166.0    257.0    261.0    224.0    1119.0
105823  다사313460    213.0    200.0    195.0    281.0    224.0    1113.0
107888  다사322486    244.0    174.0    218.0    269.0    200.0    1105.0
86651   다사245328    226.0    193.0    233.0    305.0    145.0    1102.0
102672  다사300488    234.0    144.0    238.0    311.0    173.0    1100.0
108751  다사326480    247.0    147.0    169.0    327.0    185.0    1075.0
103382  다사303454    196.0    231.0    242.0    241.0    164.0    1074.0
103873  다사305448    259.0    128.0    215.0    300.0    152.0    1054.0
109808  다사331498    182.0    258.0    262.0    232.0    113.0    1047.0
107395  다사320436    190.0    300.0    255.0    167.0    126.0    1038.0
109758  다사331428    201.0    188.0    171.0    245.0    231.0    1036.0
85501   다사241332    170.0    168.0    346.0    236.0    114.0    1034.0
105535  다사312408    206.0    178.0    195.0    260.0    186.0    1025.0
97561   다사281354    222.0    229.0    166.0    230.0    165.0    1012.0
108718  다사326447    217.0    166.0    286.0    247.0     94.0    1010.0
107788  다사322386    182.0    192.0    211.0    228.0    182.0     995.0
108725  다사326454    188.0    230.0    225.0    239.0    110.0     992.0
84506   다사237424    147.0    221.0    209.0    214.0    196.0     987.0
...          ...      ...      ...      ...      ...      ...       ...
37976   다사037606      0.0      0.0      0.0      0.0      0.0       0.0
37975   다사037605      0.0      0.0      0.0      0.0      0.0       0.0
37999   다사037640      0.0      0.0      0.0      0.0      0.0       0.0
38000   다사037641      0.0      0.0      0.0      0.0      0.0       0.0
38001   다사037642      0.0      0.0      0.0      0.0      0.0       0.0
38002   다사037643      0.0      0.0      0.0      0.0      0.0       0.0
38025   다사037666      0.0      0.0      0.0      0.0      0.0       0.0
38024   다사037665      0.0      0.0      0.0      0.0      0.0       0.0
38023   다사037664      0.0      0.0      0.0      0.0      0.0       0.0
38022   다사037663      0.0      0.0      0.0      0.0      0.0       0.0
38021   다사037662      0.0      0.0      0.0      0.0      0.0       0.0
38020   다사037661      0.0      0.0      0.0      0.0      0.0       0.0
38019   다사037660      0.0      0.0      0.0      0.0      0.0       0.0
38018   다사037659      0.0      0.0      0.0      0.0      0.0       0.0
38017   다사037658      0.0      0.0      0.0      0.0      0.0       0.0
38016   다사037657      0.0      0.0      0.0      0.0      0.0       0.0
38015   다사037656      0.0      0.0      0.0      0.0      0.0       0.0
38014   다사037655      0.0      0.0      0.0      0.0      0.0       0.0
38013   다사037654      0.0      0.0      0.0      0.0      0.0       0.0
38012   다사037653      0.0      0.0      0.0      0.0      0.0       0.0
38011   다사037652      0.0      0.0      0.0      0.0      0.0       0.0
38010   다사037651      0.0      0.0      0.0      0.0      0.0       0.0
38009   다사037650      0.0      0.0      0.0      0.0      0.0       0.0
38008   다사037649      0.0      0.0      0.0      0.0      0.0       0.0
38007   다사037648      0.0      0.0      0.0      0.0      0.0       0.0
38006   다사037647      0.0      0.0      0.0      0.0      0.0       0.0
38005   다사037646      0.0      0.0      0.0      0.0      0.0       0.0
38004   다사037645      0.0      0.0      0.0      0.0      0.0       0.0
38003   다사037644      0.0      0.0      0.0      0.0      0.0       0.0
113555  다사376538      0.0      0.0      0.0      0.0      0.0       0.0

[113556 rows x 7 columns]

In [17]:
df2.to_csv("인천시_격자_100M_20-60대_합.csv", encoding = "CP949", index = False)